export type MatchSide = "teamAId" | "teamBId";

export type KnockoutFixture = {
  matchNumber: number;
  round: number;
  date: Date;
  stadiumName: string;
  teamASource: string;
  teamBSource: string;
};

export const roundOf32ThirdPlaceSlotOrder = [
  { groupWinnerSlot: "1A", matchNumber: 79 },
  { groupWinnerSlot: "1B", matchNumber: 85 },
  { groupWinnerSlot: "1D", matchNumber: 81 },
  { groupWinnerSlot: "1E", matchNumber: 74 },
  { groupWinnerSlot: "1G", matchNumber: 82 },
  { groupWinnerSlot: "1I", matchNumber: 77 },
  { groupWinnerSlot: "1K", matchNumber: 87 },
  { groupWinnerSlot: "1L", matchNumber: 80 },
] as const;

export const roundOf32Assignments = {
  73: { teamAId: "2A", teamBId: "2B" },
  74: { teamAId: "1E", teamBId: "3" },
  75: { teamAId: "1F", teamBId: "2C" },
  76: { teamAId: "1C", teamBId: "2F" },
  77: { teamAId: "1I", teamBId: "3" },
  78: { teamAId: "2E", teamBId: "2I" },
  79: { teamAId: "1A", teamBId: "3" },
  80: { teamAId: "1L", teamBId: "3" },
  81: { teamAId: "1D", teamBId: "3" },
  82: { teamAId: "1G", teamBId: "3" },
  83: { teamAId: "2K", teamBId: "2L" },
  84: { teamAId: "1H", teamBId: "2J" },
  85: { teamAId: "1B", teamBId: "3" },
  86: { teamAId: "1J", teamBId: "2H" },
  87: { teamAId: "1K", teamBId: "3" },
  88: { teamAId: "2D", teamBId: "2G" },
} as const satisfies Record<number, Record<MatchSide, string>>;

export const knockoutAdvanceSlots = {
  73: [{ matchNumber: 90, side: "teamAId" }],
  74: [{ matchNumber: 89, side: "teamAId" }],
  75: [{ matchNumber: 90, side: "teamBId" }],
  76: [{ matchNumber: 91, side: "teamAId" }],
  77: [{ matchNumber: 89, side: "teamBId" }],
  78: [{ matchNumber: 91, side: "teamBId" }],
  79: [{ matchNumber: 92, side: "teamAId" }],
  80: [{ matchNumber: 92, side: "teamBId" }],
  81: [{ matchNumber: 94, side: "teamAId" }],
  82: [{ matchNumber: 94, side: "teamBId" }],
  83: [{ matchNumber: 93, side: "teamAId" }],
  84: [{ matchNumber: 93, side: "teamBId" }],
  85: [{ matchNumber: 96, side: "teamAId" }],
  86: [{ matchNumber: 95, side: "teamAId" }],
  87: [{ matchNumber: 96, side: "teamBId" }],
  88: [{ matchNumber: 95, side: "teamBId" }],
  89: [{ matchNumber: 97, side: "teamAId" }],
  90: [{ matchNumber: 97, side: "teamBId" }],
  91: [{ matchNumber: 99, side: "teamAId" }],
  92: [{ matchNumber: 99, side: "teamBId" }],
  93: [{ matchNumber: 98, side: "teamAId" }],
  94: [{ matchNumber: 98, side: "teamBId" }],
  95: [{ matchNumber: 100, side: "teamAId" }],
  96: [{ matchNumber: 100, side: "teamBId" }],
  97: [{ matchNumber: 101, side: "teamAId" }],
  98: [{ matchNumber: 101, side: "teamBId" }],
  99: [{ matchNumber: 102, side: "teamAId" }],
  100: [{ matchNumber: 102, side: "teamBId" }],
  101: [
    { matchNumber: 104, side: "teamAId" },
    { matchNumber: 103, side: "teamAId", loser: true },
  ],
  102: [
    { matchNumber: 104, side: "teamBId" },
    { matchNumber: 103, side: "teamBId", loser: true },
  ],
} as const satisfies Record<
  number,
  Array<{ matchNumber: number; side: MatchSide; loser?: true }>
>;

export const seedKnockoutMatches: KnockoutFixture[] = [
  { matchNumber: 73, round: 4, date: new Date("2026-06-28T19:00:00Z"), stadiumName: "SoFi Stadium", teamASource: "2º Grupo A", teamBSource: "2º Grupo B" },
  { matchNumber: 74, round: 4, date: new Date("2026-06-29T16:00:00Z"), stadiumName: "Gillette Stadium", teamASource: "1º Grupo E", teamBSource: "3º Grupo A/B/C/D/F" },
  { matchNumber: 75, round: 4, date: new Date("2026-06-29T22:30:00Z"), stadiumName: "Estadio BBVA", teamASource: "1º Grupo F", teamBSource: "2º Grupo C" },
  { matchNumber: 76, round: 4, date: new Date("2026-06-30T00:00:00Z"), stadiumName: "NRG Stadium", teamASource: "1º Grupo C", teamBSource: "2º Grupo F" },
  { matchNumber: 77, round: 4, date: new Date("2026-06-30T21:00:00Z"), stadiumName: "MetLife Stadium", teamASource: "1º Grupo I", teamBSource: "3º Grupo C/D/F/G/H" },
  { matchNumber: 78, round: 4, date: new Date("2026-06-30T17:00:00Z"), stadiumName: "AT&T Stadium", teamASource: "2º Grupo E", teamBSource: "2º Grupo I" },
  { matchNumber: 79, round: 4, date: new Date("2026-07-01T01:00:00Z"), stadiumName: "Estadio Azteca", teamASource: "1º Grupo A", teamBSource: "3º Grupo C/E/F/H/I" },
  { matchNumber: 80, round: 4, date: new Date("2026-07-01T16:00:00Z"), stadiumName: "Mercedes-Benz Stadium", teamASource: "1º Grupo L", teamBSource: "3º Grupo E/H/I/J/K" },
  { matchNumber: 81, round: 4, date: new Date("2026-07-02T00:00:00Z"), stadiumName: "Levi's Stadium", teamASource: "1º Grupo D", teamBSource: "3º Grupo B/E/F/I/J" },
  { matchNumber: 82, round: 4, date: new Date("2026-07-01T20:00:00Z"), stadiumName: "Lumen Field", teamASource: "1º Grupo G", teamBSource: "3º Grupo A/E/H/I/J" },
  { matchNumber: 83, round: 4, date: new Date("2026-07-02T16:00:00Z"), stadiumName: "BMO Field", teamASource: "2º Grupo K", teamBSource: "2º Grupo L" },
  { matchNumber: 84, round: 4, date: new Date("2026-07-02T19:00:00Z"), stadiumName: "SoFi Stadium", teamASource: "1º Grupo H", teamBSource: "2º Grupo J" },
  { matchNumber: 85, round: 4, date: new Date("2026-07-03T03:00:00Z"), stadiumName: "BC Place", teamASource: "1º Grupo B", teamBSource: "3º Grupo E/F/G/I/J" },
  { matchNumber: 86, round: 4, date: new Date("2026-07-03T22:00:00Z"), stadiumName: "Hard Rock Stadium", teamASource: "1º Grupo J", teamBSource: "2º Grupo H" },
  { matchNumber: 87, round: 4, date: new Date("2026-07-04T01:30:00Z"), stadiumName: "Arrowhead Stadium", teamASource: "1º Grupo K", teamBSource: "3º Grupo D/E/I/J/L" },
  { matchNumber: 88, round: 4, date: new Date("2026-07-03T18:00:00Z"), stadiumName: "AT&T Stadium", teamASource: "2º Grupo D", teamBSource: "2º Grupo G" },
  { matchNumber: 89, round: 5, date: new Date("2026-07-04T21:00:00Z"), stadiumName: "Lincoln Financial Field", teamASource: "Vencedor da Partida 74", teamBSource: "Vencedor da Partida 77" },
  { matchNumber: 90, round: 5, date: new Date("2026-07-04T17:00:00Z"), stadiumName: "NRG Stadium", teamASource: "Vencedor da Partida 73", teamBSource: "Vencedor da Partida 75" },
  { matchNumber: 91, round: 5, date: new Date("2026-07-05T20:00:00Z"), stadiumName: "MetLife Stadium", teamASource: "Vencedor da Partida 76", teamBSource: "Vencedor da Partida 78" },
  { matchNumber: 92, round: 5, date: new Date("2026-07-06T00:00:00Z"), stadiumName: "Estadio Azteca", teamASource: "Vencedor da Partida 79", teamBSource: "Vencedor da Partida 80" },
  { matchNumber: 93, round: 5, date: new Date("2026-07-06T19:00:00Z"), stadiumName: "AT&T Stadium", teamASource: "Vencedor da Partida 83", teamBSource: "Vencedor da Partida 84" },
  { matchNumber: 94, round: 5, date: new Date("2026-07-07T00:00:00Z"), stadiumName: "Lumen Field", teamASource: "Vencedor da Partida 81", teamBSource: "Vencedor da Partida 82" },
  { matchNumber: 95, round: 5, date: new Date("2026-07-07T16:00:00Z"), stadiumName: "Mercedes-Benz Stadium", teamASource: "Vencedor da Partida 86", teamBSource: "Vencedor da Partida 88" },
  { matchNumber: 96, round: 5, date: new Date("2026-07-07T20:00:00Z"), stadiumName: "BC Place", teamASource: "Vencedor da Partida 85", teamBSource: "Vencedor da Partida 87" },
  { matchNumber: 97, round: 6, date: new Date("2026-07-09T20:00:00Z"), stadiumName: "Gillette Stadium", teamASource: "Vencedor da Partida 89", teamBSource: "Vencedor da Partida 90" },
  { matchNumber: 98, round: 6, date: new Date("2026-07-10T19:00:00Z"), stadiumName: "SoFi Stadium", teamASource: "Vencedor da Partida 93", teamBSource: "Vencedor da Partida 94" },
  { matchNumber: 99, round: 6, date: new Date("2026-07-11T21:00:00Z"), stadiumName: "Hard Rock Stadium", teamASource: "Vencedor da Partida 91", teamBSource: "Vencedor da Partida 92" },
  { matchNumber: 100, round: 6, date: new Date("2026-07-12T01:00:00Z"), stadiumName: "Arrowhead Stadium", teamASource: "Vencedor da Partida 95", teamBSource: "Vencedor da Partida 96" },
  { matchNumber: 101, round: 7, date: new Date("2026-07-14T19:00:00Z"), stadiumName: "AT&T Stadium", teamASource: "Vencedor da Partida 97", teamBSource: "Vencedor da Partida 98" },
  { matchNumber: 102, round: 7, date: new Date("2026-07-15T19:00:00Z"), stadiumName: "Mercedes-Benz Stadium", teamASource: "Vencedor da Partida 99", teamBSource: "Vencedor da Partida 100" },
  { matchNumber: 103, round: 8, date: new Date("2026-07-18T22:00:00Z"), stadiumName: "Hard Rock Stadium", teamASource: "Perdedor da Partida 101", teamBSource: "Perdedor da Partida 102" },
  { matchNumber: 104, round: 9, date: new Date("2026-07-19T19:00:00Z"), stadiumName: "MetLife Stadium", teamASource: "Vencedor da Partida 101", teamBSource: "Vencedor da Partida 102" },
];

const thirdPlaceMatrixRows = `
EFGHIJKL:EJIFHGLK
DFGHIJKL:HGIDJFLK
DEGHIJKL:EJIDHGLK
DEFHIJKL:EJIDHFLK
DEFGIJKL:EGIDJFLK
DEFGHJKL:EGJDHFLK
DEFGHIKL:EGIDHFLK
DEFGHIJL:EGJDHFLI
DEFGHIJK:EGJDHFIK
CFGHIJKL:HGICJFLK
CEGHIJKL:EJICHGLK
CEFHIJKL:EJICHFLK
CEFGIJKL:EGICJFLK
CEFGHJKL:EGJCHFLK
CEFGHIKL:EGICHFLK
CEFGHIJL:EGJCHFLI
CEFGHIJK:EGJCHFIK
CDGHIJKL:HGICJDLK
CDFHIJKL:CJIDHFLK
CDFGIJKL:CGIDJFLK
CDFGHJKL:CGJDHFLK
CDFGHIKL:CGIDHFLK
CDFGHIJL:CGJDHFLI
CDFGHIJK:CGJDHFIK
CDEHIJKL:EJICHDLK
CDEGIJKL:EGICJDLK
CDEGHJKL:EGJCHDLK
CDEGHIKL:EGICHDLK
CDEGHIJL:EGJCHDLI
CDEGHIJK:EGJCHDIK
CDEFIJKL:CJEDIFLK
CDEFHJKL:CJEDHFLK
CDEFHIKL:CEIDHFLK
CDEFHIJL:CJEDHFLI
CDEFHIJK:CJEDHFIK
CDEFGJKL:CGEDJFLK
CDEFGIKL:CGEDIFLK
CDEFGIJL:CGEDJFLI
CDEFGIJK:CGEDJFIK
CDEFGHKL:CGEDHFLK
CDEFGHJL:CGJDHFLE
CDEFGHJK:CGJDHFEK
CDEFGHIL:CGEDHFLI
CDEFGHIK:CGEDHFIK
CDEFGHIJ:CGJDHFEI
BFGHIJKL:HJBFIGLK
BEGHIJKL:EJIBHGLK
BEFHIJKL:EJBFIHLK
BEFGIJKL:EJBFIGLK
BEFGHJKL:EJBFHGLK
BEFGHIKL:EGBFIHLK
BEFGHIJL:EJBFHGLI
BEFGHIJK:EJBFHGIK
BDGHIJKL:HJBDIGLK
BDFHIJKL:HJBDIFLK
BDFGIJKL:IGBDJFLK
BDFGHJKL:HGBDJFLK
BDFGHIKL:HGBDIFLK
BDFGHIJL:HGBDJFLI
BDFGHIJK:HGBDJFIK
BDEHIJKL:EJBDIHLK
BDEGIJKL:EJBDIGLK
BDEGHJKL:EJBDHGLK
BDEGHIKL:EGBDIHLK
BDEGHIJL:EJBDHGLI
BDEGHIJK:EJBDHGIK
BDEFIJKL:EJBDIFLK
BDEFHJKL:EJBDHFLK
BDEFHIKL:EIBDHFLK
BDEFHIJL:EJBDHFLI
BDEFHIJK:EJBDHFIK
BDEFGJKL:EGBDJFLK
BDEFGIKL:EGBDIFLK
BDEFGIJL:EGBDJFLI
BDEFGIJK:EGBDJFIK
BDEFGHKL:EGBDHFLK
BDEFGHJL:HGBDJFLE
BDEFGHJK:HGBDJFEK
BDEFGHIL:EGBDHFLI
BDEFGHIK:EGBDHFIK
BDEFGHIJ:HGBDJFEI
BCGHIJKL:HJBCIGLK
BCFHIJKL:HJBCIFLK
BCFGIJKL:IGBCJFLK
BCFGHJKL:HGBCJFLK
BCFGHIKL:HGBCIFLK
BCFGHIJL:HGBCJFLI
BCFGHIJK:HGBCJFIK
BCEHIJKL:EJBCIHLK
BCEGIJKL:EJBCIGLK
BCEGHJKL:EJBCHGLK
BCEGHIKL:EGBCIHLK
BCEGHIJL:EJBCHGLI
BCEGHIJK:EJBCHGIK
BCEFIJKL:EJBCIFLK
BCEFHJKL:EJBCHFLK
BCEFHIKL:EIBCHFLK
BCEFHIJL:EJBCHFLI
BCEFHIJK:EJBCHFIK
BCEFGJKL:EGBCJFLK
BCEFGIKL:EGBCIFLK
BCEFGIJL:EGBCJFLI
BCEFGIJK:EGBCJFIK
BCEFGHKL:EGBCHFLK
BCEFGHJL:HGBCJFLE
BCEFGHJK:HGBCJFEK
BCEFGHIL:EGBCHFLI
BCEFGHIK:EGBCHFIK
BCEFGHIJ:HGBCJFEI
BCDHIJKL:HJBCIDLK
BCDGIJKL:IGBCJDLK
BCDGHJKL:HGBCJDLK
BCDGHIKL:HGBCIDLK
BCDGHIJL:HGBCJDLI
BCDGHIJK:HGBCJDIK
BCDFIJKL:CJBDIFLK
BCDFHJKL:CJBDHFLK
BCDFHIKL:CIBDHFLK
BCDFHIJL:CJBDHFLI
BCDFHIJK:CJBDHFIK
BCDFGJKL:CGBDJFLK
BCDFGIKL:CGBDIFLK
BCDFGIJL:CGBDJFLI
BCDFGIJK:CGBDJFIK
BCDFGHKL:CGBDHFLK
BCDFGHJL:CGBDHFLJ
BCDFGHJK:HGBCJFDK
BCDFGHIL:CGBDHFLI
BCDFGHIK:CGBDHFIK
BCDFGHIJ:HGBCJFDI
BCDEIJKL:EJBCIDLK
BCDEHJKL:EJBCHDLK
BCDEHIKL:EIBCHDLK
BCDEHIJL:EJBCHDLI
BCDEHIJK:EJBCHDIK
BCDEGJKL:EGBCJDLK
BCDEGIKL:EGBCIDLK
BCDEGIJL:EGBCJDLI
BCDEGIJK:EGBCJDIK
BCDEGHKL:EGBCHDLK
BCDEGHJL:HGBCJDLE
BCDEGHJK:HGBCJDEK
BCDEGHIL:EGBCHDLI
BCDEGHIK:EGBCHDIK
BCDEGHIJ:HGBCJDEI
BCDEFJKL:CJBDEFLK
BCDEFIKL:CEBDIFLK
BCDEFIJL:CJBDEFLI
BCDEFIJK:CJBDEFIK
BCDEFHKL:CEBDHFLK
BCDEFHJL:CJBDHFLE
BCDEFHJK:CJBDHFEK
BCDEFHIL:CEBDHFLI
BCDEFHIK:CEBDHFIK
BCDEFHIJ:CJBDHFEI
BCDEFGKL:CGBDEFLK
BCDEFGJL:CGBDJFLE
BCDEFGJK:CGBDJFEK
BCDEFGIL:CGBDEFLI
BCDEFGIK:CGBDEFIK
BCDEFGIJ:CGBDJFEI
BCDEFGHL:CGBDHFLE
BCDEFGHK:CGBDHFEK
BCDEFGHJ:HGBCJFDE
BCDEFGHI:CGBDHFEI
AFGHIJKL:HJIFAGLK
AEGHIJKL:EJIAHGLK
AEFHIJKL:EJIFAHLK
AEFGIJKL:EJIFAGLK
AEFGHJKL:EGJFAHLK
AEFGHIKL:EGIFAHLK
AEFGHIJL:EGJFAHLI
AEFGHIJK:EGJFAHIK
ADGHIJKL:HJIDAGLK
ADFHIJKL:HJIDAFLK
ADFGIJKL:IGJDAFLK
ADFGHJKL:HGJDAFLK
ADFGHIKL:HGIDAFLK
ADFGHIJL:HGJDAFLI
ADFGHIJK:HGJDAFIK
ADEHIJKL:EJIDAHLK
ADEGIJKL:EJIDAGLK
ADEGHJKL:EGJDAHLK
ADEGHIKL:EGIDAHLK
ADEGHIJL:EGJDAHLI
ADEGHIJK:EGJDAHIK
ADEFIJKL:EJIDAFLK
ADEFHJKL:HJEDAFLK
ADEFHIKL:HEIDAFLK
ADEFHIJL:HJEDAFLI
ADEFHIJK:HJEDAFIK
ADEFGJKL:EGJDAFLK
ADEFGIKL:EGIDAFLK
ADEFGIJL:EGJDAFLI
ADEFGIJK:EGJDAFIK
ADEFGHKL:HGEDAFLK
ADEFGHJL:HGJDAFLE
ADEFGHJK:HGJDAFEK
ADEFGHIL:HGEDAFLI
ADEFGHIK:HGEDAFIK
ADEFGHIJ:HGJDAFEI
ACGHIJKL:HJICAGLK
ACFHIJKL:HJICAFLK
ACFGIJKL:IGJCAFLK
ACFGHJKL:HGJCAFLK
ACFGHIKL:HGICAFLK
ACFGHIJL:HGJCAFLI
ACFGHIJK:HGJCAFIK
ACEHIJKL:EJICAHLK
ACEGIJKL:EJICAGLK
ACEGHJKL:EGJCAHLK
ACEGHIKL:EGICAHLK
ACEGHIJL:EGJCAHLI
ACEGHIJK:EGJCAHIK
ACEFIJKL:EJICAFLK
ACEFHJKL:HJECAFLK
ACEFHIKL:HEICAFLK
ACEFHIJL:HJECAFLI
ACEFHIJK:HJECAFIK
ACEFGJKL:EGJCAFLK
ACEFGIKL:EGICAFLK
ACEFGIJL:EGJCAFLI
ACEFGIJK:EGJCAFIK
ACEFGHKL:HGECAFLK
ACEFGHJL:HGJCAFLE
ACEFGHJK:HGJCAFEK
ACEFGHIL:HGECAFLI
ACEFGHIK:HGECAFIK
ACEFGHIJ:HGJCAFEI
ACDHIJKL:HJICADLK
ACDGIJKL:IGJCADLK
ACDGHJKL:HGJCADLK
ACDGHIKL:HGICADLK
ACDGHIJL:HGJCADLI
ACDGHIJK:HGJCADIK
ACDFIJKL:CJIDAFLK
ACDFHJKL:HJFCADLK
ACDFHIKL:HFICADLK
ACDFHIJL:HJFCADLI
ACDFHIJK:HJFCADIK
ACDFGJKL:CGJDAFLK
ACDFGIKL:CGIDAFLK
ACDFGIJL:CGJDAFLI
ACDFGIJK:CGJDAFIK
ACDFGHKL:HGFCADLK
ACDFGHJL:CGJDAFLH
ACDFGHJK:HGJCAFDK
ACDFGHIL:HGFCADLI
ACDFGHIK:HGFCADIK
ACDFGHIJ:HGJCAFDI
ACDEIJKL:EJICADLK
ACDEHJKL:HJECADLK
ACDEHIKL:HEICADLK
ACDEHIJL:HJECADLI
ACDEHIJK:HJECADIK
ACDEGJKL:EGJCADLK
ACDEGIKL:EGICADLK
ACDEGIJL:EGJCADLI
ACDEGIJK:EGJCADIK
ACDEGHKL:HGECADLK
ACDEGHJL:HGJCADLE
ACDEGHJK:HGJCADEK
ACDEGHIL:HGECADLI
ACDEGHIK:HGECADIK
ACDEGHIJ:HGJCADEI
ACDEFJKL:CJEDAFLK
ACDEFIKL:CEIDAFLK
ACDEFIJL:CJEDAFLI
ACDEFIJK:CJEDAFIK
ACDEFHKL:HEFCADLK
ACDEFHJL:HJFCADLE
ACDEFHJK:HJECAFDK
ACDEFHIL:HEFCADLI
ACDEFHIK:HEFCADIK
ACDEFHIJ:HJECAFDI
ACDEFGKL:CGEDAFLK
ACDEFGJL:CGJDAFLE
ACDEFGJK:CGJDAFEK
ACDEFGIL:CGEDAFLI
ACDEFGIK:CGEDAFIK
ACDEFGIJ:CGJDAFEI
ACDEFGHL:HGFCADLE
ACDEFGHK:HGECAFDK
ACDEFGHJ:HGJCAFDE
ACDEFGHI:HGECAFDI
ABGHIJKL:HJBAIGLK
ABFHIJKL:HJBAIFLK
ABFGIJKL:IJBFAGLK
ABFGHJKL:HJBFAGLK
ABFGHIKL:HGBAIFLK
ABFGHIJL:HJBFAGLI
ABFGHIJK:HJBFAGIK
ABEHIJKL:EJBAIHLK
ABEGIJKL:EJBAIGLK
ABEGHJKL:EJBAHGLK
ABEGHIKL:EGBAIHLK
ABEGHIJL:EJBAHGLI
ABEGHIJK:EJBAHGIK
ABEFIJKL:EJBAIFLK
ABEFHJKL:EJBFAHLK
ABEFHIKL:EIBFAHLK
ABEFHIJL:EJBFAHLI
ABEFHIJK:EJBFAHIK
ABEFGJKL:EJBFAGLK
ABEFGIKL:EGBAIFLK
ABEFGIJL:EJBFAGLI
ABEFGIJK:EJBFAGIK
ABEFGHKL:EGBFAHLK
ABEFGHJL:HJBFAGLE
ABEFGHJK:HJBFAGEK
ABEFGHIL:EGBFAHLI
ABEFGHIK:EGBFAHIK
ABEFGHIJ:HJBFAGEI
ABDHIJKL:IJBDAHLK
ABDGIJKL:IJBDAGLK
ABDGHJKL:HJBDAGLK
ABDGHIKL:IGBDAHLK
ABDGHIJL:HJBDAGLI
ABDGHIJK:HJBDAGIK
ABDFIJKL:IJBDAFLK
ABDFHJKL:HJBDAFLK
ABDFHIKL:HIBDAFLK
ABDFHIJL:HJBDAFLI
ABDFHIJK:HJBDAFIK
ABDFGJKL:FJBDAGLK
ABDFGIKL:IGBDAFLK
ABDFGIJL:FJBDAGLI
ABDFGIJK:FJBDAGIK
ABDFGHKL:HGBDAFLK
ABDFGHJL:HGBDAFLJ
ABDFGHJK:HGBDAFJK
ABDFGHIL:HGBDAFLI
ABDFGHIK:HGBDAFIK
ABDFGHIJ:HGBDAFIJ
ABDEIJKL:EJBAIDLK
ABDEHJKL:EJBDAHLK
ABDEHIKL:EIBDAHLK
ABDEHIJL:EJBDAHLI
ABDEHIJK:EJBDAHIK
ABDEGJKL:EJBDAGLK
ABDEGIKL:EGBAIDLK
ABDEGIJL:EJBDAGLI
ABDEGIJK:EJBDAGIK
ABDEGHKL:EGBDAHLK
ABDEGHJL:HJBDAGLE
ABDEGHJK:HJBDAGEK
ABDEGHIL:EGBDAHLI
ABDEGHIK:EGBDAHIK
ABDEGHIJ:HJBDAGEI
ABDEFJKL:EJBDAFLK
ABDEFIKL:EIBDAFLK
ABDEFIJL:EJBDAFLI
ABDEFIJK:EJBDAFIK
ABDEFHKL:HEBDAFLK
ABDEFHJL:HJBDAFLE
ABDEFHJK:HJBDAFEK
ABDEFHIL:HEBDAFLI
ABDEFHIK:HEBDAFIK
ABDEFHIJ:HJBDAFEI
ABDEFGKL:EGBDAFLK
ABDEFGJL:EGBDAFLJ
ABDEFGJK:EGBDAFJK
ABDEFGIL:EGBDAFLI
ABDEFGIK:EGBDAFIK
ABDEFGIJ:EGBDAFIJ
ABDEFGHL:HGBDAFLE
ABDEFGHK:HGBDAFEK
ABDEFGHJ:HGBDAFEJ
ABDEFGHI:HGBDAFEI
ABCHIJKL:IJBCAHLK
ABCGIJKL:IJBCAGLK
ABCGHJKL:HJBCAGLK
ABCGHIKL:IGBCAHLK
ABCGHIJL:HJBCAGLI
ABCGHIJK:HJBCAGIK
ABCFIJKL:IJBCAFLK
ABCFHJKL:HJBCAFLK
ABCFHIKL:HIBCAFLK
ABCFHIJL:HJBCAFLI
ABCFHIJK:HJBCAFIK
ABCFGJKL:CJBFAGLK
ABCFGIKL:IGBCAFLK
ABCFGIJL:CJBFAGLI
ABCFGIJK:CJBFAGIK
ABCFGHKL:HGBCAFLK
ABCFGHJL:HGBCAFLJ
ABCFGHJK:HGBCAFJK
ABCFGHIL:HGBCAFLI
ABCFGHIK:HGBCAFIK
ABCFGHIJ:HGBCAFIJ
ABCEIJKL:EJBAICLK
ABCEHJKL:EJBCAHLK
ABCEHIKL:EIBCAHLK
ABCEHIJL:EJBCAHLI
ABCEHIJK:EJBCAHIK
ABCEGJKL:EJBCAGLK
ABCEGIKL:EGBAICLK
ABCEGIJL:EJBCAGLI
ABCEGIJK:EJBCAGIK
ABCEGHKL:EGBCAHLK
ABCEGHJL:HJBCAGLE
ABCEGHJK:HJBCAGEK
ABCEGHIL:EGBCAHLI
ABCEGHIK:EGBCAHIK
ABCEGHIJ:HJBCAGEI
ABCEFJKL:EJBCAFLK
ABCEFIKL:EIBCAFLK
ABCEFIJL:EJBCAFLI
ABCEFIJK:EJBCAFIK
ABCEFHKL:HEBCAFLK
ABCEFHJL:HJBCAFLE
ABCEFHJK:HJBCAFEK
ABCEFHIL:HEBCAFLI
ABCEFHIK:HEBCAFIK
ABCEFHIJ:HJBCAFEI
ABCEFGKL:EGBCAFLK
ABCEFGJL:EGBCAFLJ
ABCEFGJK:EGBCAFJK
ABCEFGIL:EGBCAFLI
ABCEFGIK:EGBCAFIK
ABCEFGIJ:EGBCAFIJ
ABCEFGHL:HGBCAFLE
ABCEFGHK:HGBCAFEK
ABCEFGHJ:HGBCAFEJ
ABCEFGHI:HGBCAFEI
ABCDIJKL:IJBCADLK
ABCDHJKL:HJBCADLK
ABCDHIKL:HIBCADLK
ABCDHIJL:HJBCADLI
ABCDHIJK:HJBCADIK
ABCDGJKL:CJBDAGLK
ABCDGIKL:IGBCADLK
ABCDGIJL:CJBDAGLI
ABCDGIJK:CJBDAGIK
ABCDGHKL:HGBCADLK
ABCDGHJL:HGBCADLJ
ABCDGHJK:HGBCADJK
ABCDGHIL:HGBCADLI
ABCDGHIK:HGBCADIK
ABCDGHIJ:HGBCADIJ
ABCDFJKL:CJBDAFLK
ABCDFIKL:CIBDAFLK
ABCDFIJL:CJBDAFLI
ABCDFIJK:CJBDAFIK
ABCDFHKL:HFBCADLK
ABCDFHJL:CJBDAFLH
ABCDFHJK:HJBCAFDK
ABCDFHIL:HFBCADLI
ABCDFHIK:HFBCADIK
ABCDFHIJ:HJBCAFDI
ABCDFGKL:CGBDAFLK
ABCDFGJL:CGBDAFLJ
ABCDFGJK:CGBDAFJK
ABCDFGIL:CGBDAFLI
ABCDFGIK:CGBDAFIK
ABCDFGIJ:CGBDAFIJ
ABCDFGHL:CGBDAFLH
ABCDFGHK:HGBCAFDK
ABCDFGHJ:HGBCAFDJ
ABCDFGHI:HGBCAFDI
ABCDEJKL:EJBCADLK
ABCDEIKL:EIBCADLK
ABCDEIJL:EJBCADLI
ABCDEIJK:EJBCADIK
ABCDEHKL:HEBCADLK
ABCDEHJL:HJBCADLE
ABCDEHJK:HJBCADEK
ABCDEHIL:HEBCADLI
ABCDEHIK:HEBCADIK
ABCDEHIJ:HJBCADEI
ABCDEGKL:EGBCADLK
ABCDEGJL:EGBCADLJ
ABCDEGJK:EGBCADJK
ABCDEGIL:EGBCADLI
ABCDEGIK:EGBCADIK
ABCDEGIJ:EGBCADIJ
ABCDEGHL:HGBCADLE
ABCDEGHK:HGBCADEK
ABCDEGHJ:HGBCADEJ
ABCDEGHI:HGBCADEI
ABCDEFKL:CEBDAFLK
ABCDEFJL:CJBDAFLE
ABCDEFJK:CJBDAFEK
ABCDEFIL:CEBDAFLI
ABCDEFIK:CEBDAFIK
ABCDEFIJ:CJBDAFEI
ABCDEFHL:HFBCADLE
ABCDEFHK:HEBCAFDK
ABCDEFHJ:HJBCAFDE
ABCDEFHI:HEBCAFDI
ABCDEFGL:CGBDAFLE
ABCDEFGK:CGBDAFEK
ABCDEFGJ:CGBDAFEJ
ABCDEFGI:CGBDAFEI
ABCDEFGH:HGBCAFDE
`.trim();

export const thirdPlaceMatrix = new Map(
  thirdPlaceMatrixRows.split("\n").map((row) => {
    const [groups, slots] = row.split(":");
    return [groups ?? "", (slots ?? "").split("")] as const;
  }),
);
